githubRepoOwner: inigolabs
githubRepoName: inigo-kong
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: true
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
