FROM ghcr.io/inigolabs/inigo-kong/kong:latest

# add inigo lib
COPY libs /kong/plugins/inigo

# Run kong
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8000 8443 8001 8444
STOPSIGNAL SIGQUIT
HEALTHCHECK --interval=10s --timeout=10s --retries=10 CMD kong health
CMD ["kong", "docker-start"]
